### ISSUE TITLE
setDaysHighlight - Returns 1 day before

### ISSUE THREAD

**Issue by vbrodrigo** [maurovieirareis/hello-week#19]
The method below always returns 1 day before. In the sample, the calendar makes highlighted 2019-03-31:

setDaysHighlight([
{days: ['2019-04-01'],backgroundColor: '#999'},
])

The same issue happens in official documentation, also.

**Comment by mauroreisvieira** [comment]
Hi @vbrodrigo are you sure? I see the official documentation an I not see any issue. Can you send me a screenshot?

**Comment by vbrodrigo** [comment]
See below:

<img width="357" alt="Captura de Tela 2019-03-12 às 14 34 05" src="https://user-images.githubusercontent.com/24582321/54222357-ffafa480-44d3-11e9-9707-e1d1085eeeb3.png">

<img width="951" alt="Captura de Tela 2019-03-12 às 14 34 11" src="https://user-images.githubusercontent.com/24582321/54222362-050cef00-44d4-11e9-8615-dc7f1f412472.png">

**Comment by mauroreisvieira** [comment]
Whaaat?!?!? 
It's not happen with me, but I will go check this. 

What version are you using?

![Highlight Dates ](https://user-images.githubusercontent.com/3084774/54222885-372b4a80-44ee-11e9-8511-87c77ab6aa42.png)

**Comment by vbrodrigo** [comment]
I'm using [2.1.0] - 2019-02-24

Maybe, the trouble is my timezone (UTC -03:00 from Brazil), because i can see that you converts date to time in this method. Or not?

**Comment by mauroreisvieira** [comment]
Hum, yap. It's the problem. But I can fix this.

**Comment by vbrodrigo** [comment]
Great! Hello week was the best of calendars i could find. Beautiful and functional. Congratulations! Obrigado!

**Comment by mauroreisvieira** [comment]
Muito Obrigado @vbrodrigo .

**Comment by mauroreisvieira** [comment]
@vbrodrigo fix in new version.

**Comment by jidrone** [comment]
I have been using the 3.x versions and the issue is still present, it is like at some time at night when I check the calendar all highlighted days are one day before and the next day when I see the calendar during the morning the highlighted days are ok.

**Comment by mauroreisvieira** [comment]
Hey @jidrone version 3.x is not stable and to be honest, I don't have been working on that new version (I have been thinking about refactoring everything from scratch).

So, please use version **2.13.0** that issue was solved, you just need to pass the option `timezoneOffset` on HelloWeek initialization.

Please let me know if, the issue is still present after that.

**Comment by mauroreisvieira** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by tiojoca** [comment]
This issue persists for dates after Daylight Saving Time changes because the `timezoneOffset` will change for those dates. For example, if you're in New York (or simulate it with devtools) you get these timezones for these dates in different DST:
```
new Date('2023-07-14').getTimezoneOffset(); // => 240
new Date('2023-12-01').getTimezoneOffset(); // => 300
```

Setting the timezone to be always `dt.getTimezoneOffset()` in `setTimeZone()` and ignoring the timezone in the calendar options seems to have fixed this for me. I also started using `calendar.daysSelected` directly, since `calendar.getDays()` runs `timestampToHuman()` again on dates that have already been converted, potentially changing the date.

**Comment by mauroreisvieira** [comment]
Hey @tiojoca thanks for the reporting. 

It was a mistake from the beginning to use timestamps to compare days, I need to change that.

**Comment by olieydt** [comment]
Ive been using lastSelectedDay which is timestamp at midnight of selected day to get the picked date, month, year
```
const selectedDay = new Date(helloWeek.lastSelectedDay)
const parsedSelectedDate = { date: selectedDay.getUTCDate(), month: selectedDay.getUTCMonth(), year: selectedDay.getUTCFullYear() }
```

**Comment by meaton1206** [comment]
Not sure anyone cares anymore but......
Found this interesting piece of information about javascript dates (look at first answer):
https://stackoverflow.com/questions/7556591/is-the-javascript-date-object-always-one-day-off#:~:text=Javascript's%20Date%20class%20doesn't,%3A00%20GMT%2D0400).

Solution for me was in hello.week.js,  function setToTimestamp(date)

Changed:
return new Date(date).setHours(0, 0, 0, 0);
To:
return new Date(date.replace(/-/g, '\/').replace(/T.+/, '')).setHours(0, 0, 0, 0);
